#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.join(__dir__, '..', 'lib'))

begin
  require 'snippet_cli'
  require 'snippet_cli/banner'

  puts SnippetCli.banner
  puts

  Dry::CLI.new(SnippetCli::CLI).call
rescue Interrupt
  if defined?(SnippetCli::UI)
    puts
    SnippetCli::UI.error('Interrupted, exiting snippet_cli.')
  else
    warn "\nInterrupted."
  end
  exit 130
end
