#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.join(__dir__, '..', 'lib'))

require 'snippet_cli'
require 'snippet_cli/banner'

puts SnippetCli.banner
Dry::CLI.new(SnippetCli::CLI).call
